name: Build Surya Kernel for Droidspaces

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Work Space
        uses: actions/checkout@v4

      - name: Setup Build Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y git ccache automake flex lzop bison \
          gperf build-essential zip curl zlib1g-dev \
          libxml2-utils bzip2 libbz2-dev \
          squashfs-tools schedtool dpkg-dev liblz4-tool \
          make libssl-dev pwgen \
          bc libncurses-dev libelf-dev \
          xsltproc unzip \
          gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi \
          binutils-aarch64-linux-gnu binutils-arm-linux-gnueabi \
          clang lld llvm

      - name: Clone Kernel Source
        run: |
          git clone --depth=1 https://github.com/baikalos/android_kernel_xiaomi_surya.git kernel-source

      - name: Apply Droidspaces Config & Compile
        run: |
          cd kernel-source
          
          # 1. Run Defconfig
          make O=out surya_defconfig \
            ARCH=arm64 \
            CC=clang \
            CROSS_COMPILE=aarch64-linux-gnu- \
            CROSS_COMPILE_ARM32=arm-linux-gnueabi-
          
          # 2. Copy your droidspaces.config file to the kernel folder
          cp $GITHUB_WORKSPACE/droidspaces.config ./droidspaces.config
          
          # 3. Merge configs
          ARCH=arm64 scripts/kconfig/merge_config.sh -O out out/.config ./droidspaces.config
          
          # 4. Compile the kernel (Strictly NO LLVM FLAGS this time!)
          make -j$(nproc --all) O=out \
            ARCH=arm64 \
            CC=clang \
            CROSS_COMPILE=aarch64-linux-gnu- \
            CROSS_COMPILE_ARM32=arm-linux-gnueabi-

      - name: Upload Kernel Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Compiled-Surya-Droidspaces-Kernel
          path: |
            kernel-source/out/arch/arm64/boot/Image.gz
            kernel-source/out/arch/arm64/boot/Image.gz-dtb
            kernel-source/out/arch/arm64/boot/dtbo.img
            
